url: https://rameshnagaraj.github.io/homemade
baseurl: /homemade/

# Site settings
title: HomeMade
email: mail@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 14f065
  secondary: 0dc752
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Charan kumar 
  pic: 1
  position: Production Head
  social:
    - title: twitter
      url: #
    - title: facebook
      url: # https://www.facebook.com/charan.kumar.16
    - title: stack-overflow
      url: #

- name: Poorna Chandra
  pic: 2
  position: Distribution Head
  social:
    - title: twitter
      url: #
    - title: facebook
      url: # https://www.facebook.com/tejas.teju.7
    - title: linkedin
      url: #

- name: Naveen Kumar
  pic: 3
  position: Marketing Head
  social:
    - title: twitter
      url: #
    - title: facebook
      url: # https://www.facebook.com/Navzone
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url:
  - title: stack-overflow
    url: 
  - title: bitbucket 
    url: 
  - title: github
    url:

# Postal address (add as many lines as necessary)
address:
  - line: Yelahanka
  - line: Bangalore, KA 560097

# Build settings
markdown: kramdown
permalink: pretty
